In [2]:
import numpy as np

In [3]:
#2.1
corr = np.array([[1, 0.488, 0.478, 0.515, 0.439, 0.512, 0.491],
                  [0.488, 1, 0.664, 0.655, 0.310, 0.608, 0.779],
                  [0.478, 0.664, 1, 0.861, 0.355, 0.783, 0.668],
                  [0.515, 0.655, 0.861, 1, 0.354, 0.777, 0.653],
                  [0.439, 0.310, 0.355, 0.354, 1, 0.405, 0.306],
                  [0.512, 0.608, 0.783, 0.777, 0.405, 1, 0.652],
                  [0.491, 0.779, 0.668, 0.653, 0.306, 0.652, 1]])

vol = np.array([0.16, 0.203, 0.248, 0.271, 0.21, 0.20, 0.187])
Sigma = np.outer(vol, vol)*corr #Covariance Matrix of Returns

w_eq = np.array([0.016, 0.022, 0.052, 0.055, 0.116, 0.124, 0.615]) #given w_eq from the lecture ntoes
gamma = 3.5 #risk aversion coefficient

mu_0 = gamma*Sigma.dot(w_eq) #mu_0 calulation
print(f"mu_0:\n{np.round(mu_0,5)}")

mu_0:
[0.05513 0.09681 0.11701 0.12638 0.06024 0.09475 0.10584]


In [4]:
#2.2
gamma = 2
tau = 0.03 #uncertainty coeffient
mu_0 = gamma*Sigma.dot(w_eq) #new mu_0

Omega_0 = tau*Sigma #Omega_0 which is defined like the product between tau and Sigma
Sigma_0 = Sigma+Omega_0

w_0 = np.linalg.inv(gamma*Sigma_0).dot(mu_0) #formula for the weights to obtain market portfolio
print(f"w_0:\n{np.round(w_0,5)}\n")
print(f"The deviations between w_0 and w_eq are:\n{np.round(w_0-w_eq,5)}")

w_0:
[0.01553 0.02136 0.05049 0.0534  0.11262 0.12039 0.59709]

The deviations between w_0 and w_eq are:
[-0.00047 -0.00064 -0.00151 -0.0016  -0.00338 -0.00361 -0.01791]


In [12]:
#2.3

p_FR = 5.2/(12.4+5.2) 
p_UK = 12.4/(12.4+5.2)

#view portfolios:
P = np.array([[0,0, -p_FR, 1, 0, -p_UK, 0],
              [0, 1, 0, 0, 0, 0, -1]])

Omega = np.array([[0.025*tau, 0],
                  [0, 0.015*tau]])
q = np.array([0.045, 0.02])

#first derived version:
mu_bar_1 = mu_0 + Omega_0.dot(P.T).dot(np.linalg.inv(P.dot(Omega_0.dot(P.T))+Omega)).dot(q-P.dot(mu_0))
Omega_bar_1 = Omega_0 - Omega_0.dot(P.T).dot(np.linalg.inv(P.dot(Omega_0.dot(P.T))+Omega)).dot(P.dot(Omega_0))

#second version:
mu_bar = (np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P))).dot((np.linalg.inv(Omega_0)).dot(mu_0)+P.T.dot(np.linalg.inv(Omega).dot(q))))
Omega_bar = np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P)))

print(f"Posterior expectation of the mean return: \n {np.round(mu_bar, 5)} \n")
print(f"Posterior Covariance Matrix of the mean return: \n{np.round(Omega_bar, 5)}\n\n")

#check if the two versions coincide:
print(f"The differences of the two versions for the mean are:\n{np.round(mu_bar_1-mu_bar, 5)}\n")
print(f"The differences of the two versions for the Covariance Matrix are:\n{np.round(Omega_bar_1-Omega_bar, 5)}")



Posterior expectation of the mean return: 
 [0.03563 0.06953 0.07647 0.09123 0.03702 0.05591 0.06072] 

Posterior Covariance Matrix of the mean return: 
[[0.00075 0.00044 0.00053 0.00058 0.00043 0.00048 0.00042]
 [0.00044 0.00107 0.00091 0.00091 0.00037 0.00072 0.00091]
 [0.00053 0.00091 0.00174 0.00152 0.00053 0.00115 0.00089]
 [0.00058 0.00091 0.00152 0.00174 0.00056 0.00122 0.00089]
 [0.00043 0.00037 0.00053 0.00056 0.00132 0.00051 0.00035]
 [0.00048 0.00072 0.00115 0.00122 0.00051 0.0012  0.00072]
 [0.00042 0.00091 0.00089 0.00089 0.00035 0.00072 0.00099]]


The differences of the two versions for the mean are:
[-0. -0. -0. -0. -0. -0. -0.]

The differences of the two versions for the Covariance Matrix are:
[[ 0. -0. -0.  0.  0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0.]]


In [ ]:
#2.4
Sigma_hat = Omega_bar + Sigma
w_star = np.linalg.inv(gamma*Sigma_hat).dot(mu_bar)
print(f"Optimal unconstrained mean-variance portfolio: \n{np.round(w_star, 5)}\n")
print(f"The deviations between w_star and w_0  are:\n {np.round(w_star-w_0,5)}\n")
print(f"The deviations between w_star and w_eq are:\n {np.round(w_star-w_eq,5)}")

Optimal unconstrained mean-variance portfolio: 
[ 0.01553  0.38684 -0.04256  0.36832  0.11262 -0.10149  0.23161]

The deviations between w_star and w_0  are:
 [ 0.       0.36548 -0.09304  0.31492  0.      -0.22188 -0.36548]

The deviations between w_star and w_eq are:
 [-0.00047  0.36484 -0.09456  0.31332 -0.00338 -0.22549 -0.38339]


In [ ]:
#2.5
#using the formula derived on paper (see pdf)
Lambda_star = 1/gamma*np.linalg.inv((P.dot(Sigma.dot(P.T))+(1+1/tau)*Omega)).dot(q-(1/(1+tau)*P.dot(mu_0)))
print(f"lambda_1: {np.round(Lambda_star[0],5)}")
print(f"lambda_2: {np.round(Lambda_star[1],5)}")

lambda_1: 0.31492
lambda_2: 0.36548


In [13]:
#2.6 
#new view portfolio:
P = np.array([[0,0, -p_FR, 1, 0, -p_UK, 0],
              [0, 1, 0, 0, 0, 0, -1],
              [0, 0, 0, 0, 1, 0, 0]])

Omega = np.array([[0.025*tau, 0, 0],
                  [0, 0.015*tau, 0],
                  [0, 0, 0.04*tau]])

q = np.array([0.045, 0.02, 0.055])
mu_bar = (np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P))).dot((np.linalg.inv(Omega_0)).dot(mu_0)+P.T.dot(np.linalg.inv(Omega).dot(q))))
Omega_bar = np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P)))

Sigma_hat = Omega_bar + Sigma
w_star = np.linalg.inv(gamma*Sigma_hat).dot(mu_bar)

Lambda_star = 1/gamma*np.linalg.inv((P.dot(Sigma.dot(P.T))+(1+1/tau)*Omega)).dot(q-(1/(1+tau)*P.dot(mu_0)))

print(f"Case 1: Uncertainty of 0.04*tau \n ")
print(f"Optimal unconstrained mean-variance portfolio: \n{np.round(w_star, 5)}\n")
print(f"lambda_1: {np.round(Lambda_star[0],5)}")
print(f"lambda_2: {np.round(Lambda_star[1],5)}")
print(f"lambda_3: {np.round(Lambda_star[2],5)}")

Case 1: Uncertainty of 0.04*tau 
 
Optimal unconstrained mean-variance portfolio: 
[ 0.01553  0.3831  -0.04071  0.36207  0.22427 -0.09709  0.23534]

lambda_1: 0.30867
lambda_2: 0.36174
lambda_3: 0.11164


In [14]:
Omega = np.array([[0.025*tau, 0, 0],
                  [0, 0.015*tau, 0],
                  [0, 0, 0.01*tau]])
mu_bar = (np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P))).dot((np.linalg.inv(Omega_0)).dot(mu_0)+P.T.dot(np.linalg.inv(Omega).dot(q))))
Omega_bar = np.linalg.inv(np.linalg.inv(Omega_0)+P.T.dot(np.linalg.inv(Omega).dot(P)))

Sigma_hat = Omega_bar + Sigma
w_star = np.linalg.inv(gamma*Sigma_hat).dot(mu_bar)

Lambda_star = 1/gamma*np.linalg.inv((P.dot(Sigma.dot(P.T))+(1+1/tau)*Omega)).dot(q-(1/(1+tau)*P.dot(mu_0)))

print(f"Case 2: Uncertainty of 0.01*tau \n ")
print(f"Optimal unconstrained mean-variance portfolio: \n{np.round(w_star, 5)}\n")
print(f"lambda_1: {np.round(Lambda_star[0],5)}")
print(f"lambda_2: {np.round(Lambda_star[1],5)}")
print(f"lambda_3: {np.round(Lambda_star[2],5)}")


Case 2: Uncertainty of 0.01*tau 
 
Optimal unconstrained mean-variance portfolio: 
[ 0.01553  0.38097 -0.03966  0.35851  0.2879  -0.09458  0.23747]

lambda_1: 0.30511
lambda_2: 0.35961
lambda_3: 0.17528
